<?php
    $server = "";
    //Ordenar por orden alfabético!!
    $rutas = array(
        // API
        "api_admin_sexo" => $server . "/api/admin_create_sexo.php",
        "api_admin_user" => $server . "/api/admin_create_user.php",
        "api_admin_serie" => $server . "/api/admin_create_serie.php",
        "api_admin_users" => $server . "/api/admin_usuarios_bd.php",
        "api_admin_series" => $server . "/api/admin_series_bd.php",
        "api_admin_sexos" => $server . "/api/admin_sexos_bd.php",
        "api_admin_update_sexo" => $server . "/api/admin_update_sexo.php",
        "api_admin_update_serie" => $server . "/api/admin_update_serie.php",
        "api_admin_update_user" => $server . "/api/admin_update_user.php",
        "api_admin_select_serie" => $server . "/api/admin_select_serie.php",
        "api_admin_select_user" => $server . "/api/admin_select_user.php",
        "api_close_bd" => $server . "/api/close_bd.php",
        "api_connection_bd" => $server . "/api/connection_bd.php",
        "api_delete_user" => $server . "/api/delete_user.php",
        "api_delete_serie" => $server . "/api/delete_serie.php",
        "api_delete_sexo" => $server . "/api/delete_sexo.php",
        "api_login" => $server . "/api/login.php",
        "api_logout" => $server . "/api/logout.php",
        "api_registro" => $server . "/api/create_user.php",
        "api_select_user" => $server . "/api/select_user.php",
        "api_select_serie" => $server . "/api/select_serie.php",
        "api_select_sexo" => $server . "/api/select_sexo.php",
        "api_select_sexos" => $server . "/api/select_sexos.php",
        // CSS
        "css_login" => $server . "/assets/styles/css/login.css",
        "css_registro" => $server . "/assets/styles/css/registro.css",
        "css_web" => $server . "/assets/styles/css/web.css",
        "css_landing" => $server . "/assets/styles/css/landing.css",
        "css_master" => $server . "/assets/styles/css/master.css",
        "css_serie" => $server . "/assets/styles/css/serie.css",
        "css_imagen" => $server . "/assets/styles/css/imagen.css",
        "css_series" => $server . "/assets/styles/css/series.css",
        // Scripts
        "events_js" => $server . "/assets/scripts/events.js",
        "events_admin_user_new_js" => $server . "/assets/scripts/admin_user_new.js",
        "events_admin_user_edit_js" => $server . "/assets/scripts/admin_user_edit.js",
        "events_admin_series_edit_js" => $server . "/assets/scripts/admin_series_edit.js",
        "events_admin_series_new_js" => $server . "/assets/scripts/admin_series_new.js",
        "events_series_js" => $server . "/assets/scripts/admin_series.js",
        "events_serie_js" => $server . "/assets/scripts/serie.js",
        "events_sexos_js" => $server . "/assets/scripts/admin_sexos.js",
        "events_users_js" => $server . "/assets/scripts/admin_users.js",
        "image.js" => $server . "/assets/scripts/image.js",

        "font_material_icons" => $server . "",
        "font_font_awesome" => $server . "",
        // Formularios
        "form_about" => $server . "/forms/about_form.php",
        "form_admin_main" => $server . "/forms/admin/",
        "form_admin_series" => $server . "/forms/admin/series/series.php",
        "form_admin_series_edit" => $server . "/forms/admin/series/serie_edit.php",
        "form_admin_series_new" => $server . "/forms/admin/series/serie_new.php",
        "form_admin_sexos" => $server . "/forms/admin/sexos/sexos.php",
        "form_admin_sexos_edit" => $server . "/forms/admin/sexos/sexo_edit.php",
        "form_admin_sexos_new" => $server . "/forms/admin/sexos/sexo_new.php",
        "form_admin_users" => $server . "/forms/admin/users/users.php",
        "form_admin_users_edit" => $server . "/forms/admin/users/user_edit.php",
        "form_admin_users_new" => $server . "/forms/admin/users/user_new.php",
        "form_index" => $server . "/",
        "form_login" => $server . "/forms/login_form.php",
        "form_registro" => $server . "/forms/registro_form.php",
        "form_series" => $server . "/forms/series.php",
        // Imagenes
        "img_logo" => $server . "/assets/media/img/logo.png",
        "img_logo_ico" => $server . "/assets/media/img/logo.png",
        "img_marc" => $server . "/assets/media/img/Marc_Martinez_Mayne_1.jpeg",
        "img_series" => $server . "/assets/media/img/movie.png",
        "img_sexos" => $server . "/assets/media/img/sex-symbol.png",
        "img_users" => $server . "/assets/media/img/users.png",
        // Librerias
        "lib_bootstrap_core_css" => $server . "/assets/libs/bootstrap/css/bootstrap.min.css",
        "lib_bootstrap_js" => $server . "/assets/libs/bootstrap/js/bootstrap.min.js",
        "lib_jquery" => $server . "/assets/libs/bootstrap/js/jquery-3.3.1.min.js",
        "lib_popper" => $server . "/assets/libs/bootstrap/js/popper.min.js",
        "lib_ti" => $server . "/assets/libs/ti/ti.php",
        // Otros
        "profile" => $server . "/forms/profile.php",
        "template_master" => $server . "/assets/templates/master.php",
    );
?>